export const htmlEntityUtil = [
    {
        title: 'ASCII characters',
        symbols: [
            { symbol: '&#32;', title: 'Space' },
            { symbol: '&#33;', title: 'Exclamation mark' },
            { symbol: '&#34;', title: 'Quotation mark' },
            { symbol: '&#35;', title: 'Number sign' },
            { symbol: '&#36;', title: 'Dollar sign' },
            { symbol: '&#37;', title: 'Percent sign' },
            { symbol: '&#38;', title: 'Ampersand' },
            { symbol: '&#39;', title: 'Apostrophe' },
            { symbol: '&#40;', title: 'Opening/Left Parenthesis' },
            { symbol: '&#41;', title: 'Closing/Right Parenthesis' },
            { symbol: '&#42;', title: 'Asterisk' },
            { symbol: '&#43;', title: 'Plus sign' },
            { symbol: '&#44;', title: 'Comma' },
            { symbol: '&#45;', title: 'Hyphen' },
            { symbol: '&#46;', title: 'Period' },
            { symbol: '&#47;', title: 'Slash' },
            { symbol: '&#48;', title: 'Digit 0' },
            { symbol: '&#49;', title: 'Digit 1' },
            { symbol: '&#50;', title: 'Digit 2' },
            { symbol: '&#51;', title: 'Digit 3' },
            { symbol: '&#52;', title: 'Digit 4' },
            { symbol: '&#53;', title: 'Digit 5' },
            { symbol: '&#54;', title: 'Digit 6' },
            { symbol: '&#55;', title: 'Digit 7' },
            { symbol: '&#56;', title: 'Digit 8' },
            { symbol: '&#57;', title: 'Digit 9' },
            { symbol: '&#58;', title: 'Colon' },
            { symbol: '&#59;', title: 'Semicolon' },
            { symbol: '&#60;', title: 'Less-than' },
            { symbol: '&#61;', title: 'Equals sign' },
            { symbol: '&#62;', title: 'Greater than' },
            { symbol: '&#63;', title: 'Question mark' },
            { symbol: '&#64;', title: 'At sign' },
            { symbol: '&#65;', title: 'Uppercase A' },
            { symbol: '&#66;', title: 'Uppercase B' },
            { symbol: '&#67;', title: 'Uppercase C' },
            { symbol: '&#68;', title: 'Uppercase D' },
            { symbol: '&#69;', title: 'Uppercase E' },
            { symbol: '&#70;', title: 'Uppercase F' },
            { symbol: '&#71;', title: 'Uppercase G' },
            { symbol: '&#72;', title: 'Uppercase H' },
            { symbol: '&#73;', title: 'Uppercase I' },
            { symbol: '&#74;', title: 'Uppercase J' },
            { symbol: '&#75;', title: 'Uppercase K' },
            { symbol: '&#76;', title: 'Uppercase L' },
            { symbol: '&#77;', title: 'Uppercase M' },
            { symbol: '&#78;', title: 'Uppercase N' },
            { symbol: '&#79;', title: 'Uppercase O' },
            { symbol: '&#80;', title: 'Uppercase P' },
            { symbol: '&#81;', title: 'Uppercase Q' },
            { symbol: '&#82;', title: 'Uppercase R' },
            { symbol: '&#83;', title: 'Uppercase S' },
            { symbol: '&#84;', title: 'Uppercase T' },
            { symbol: '&#85;', title: 'Uppercase U' },
            { symbol: '&#86;', title: 'Uppercase V' },
            { symbol: '&#87;', title: 'Uppercase W' },
            { symbol: '&#88;', title: 'Uppercase X' },
            { symbol: '&#89;', title: 'Uppercase Y' },
            { symbol: '&#90;', title: 'Uppercase Z' },
            { symbol: '&#91;', title: 'Opening/Left square bracket' },
            { symbol: '&#92;', title: 'Backslash' },
            { symbol: '&#93;', title: 'Closing/Right square bracket' },
            { symbol: '&#94;', title: 'Caret' },
            { symbol: '&#95;', title: 'Underscore' },
            { symbol: '&#96;', title: 'Grave accent' },
            { symbol: '&#97;', title: 'Lowercase a' },
            { symbol: '&#98;', title: 'Lowercase b' },
            { symbol: '&#99;', title: 'Lowercase c' },
            { symbol: '&#100;', title: 'Lowercase d' },
            { symbol: '&#101;', title: 'Lowercase e' },
            { symbol: '&#102;', title: 'Lowercase f' },
            { symbol: '&#103;', title: 'Lowercase g' },
            { symbol: '&#104;', title: 'Lowercase h' },
            { symbol: '&#105;', title: 'Lowercase i' },
            { symbol: '&#106;', title: 'Lowercase j' },
            { symbol: '&#107;', title: 'Lowercase k' },
            { symbol: '&#108;', title: 'Lowercase l' },
            { symbol: '&#109;', title: 'Lowercase m' },
            { symbol: '&#110;', title: 'Lowercase n' },
            { symbol: '&#111;', title: 'Lowercase o' },
            { symbol: '&#112;', title: 'Lowercase p' },
            { symbol: '&#113;', title: 'Lowercase q' },
            { symbol: '&#114;', title: 'Lowercase r' },
            { symbol: '&#115;', title: 'Lowercase s' },
            { symbol: '&#116;', title: 'Lowercase t' },
            { symbol: '&#117;', title: 'Lowercase u' },
            { symbol: '&#118;', title: 'Lowercase v' },
            { symbol: '&#119;', title: 'Lowercase w' },
            { symbol: '&#120;', title: 'Lowercase x' },
            { symbol: '&#121;', title: 'Lowercase y' },
            { symbol: '&#122;', title: 'Lowercase z' },
            { symbol: '&#123;', title: 'Opening/Left curly brace' },
            { symbol: '&#124;', title: 'Vertical bar' },
            { symbol: '&#125;', title: 'Closing/Right curly brace' },
            { symbol: '&#126;', title: 'Tilde' },
        ]
    },
    {
        title: 'ISO-8859-1 Characters',
        symbols: [
            { symbol: '&Agrave;', title: 'Capital a with grave accent' },
            { symbol: '&Aacute;', title: 'Capital a with acute accent' },
            { symbol: '&Acirc;', title: 'Capital a with circumflex accent' },
            { symbol: '&Atilde;', title: 'Capital a with tilde' },
            { symbol: '&Auml;', title: 'Capital a with umlaut' },
            { symbol: '&Aring;', title: 'Capital a with ring' },
            { symbol: '&AElig;', title: 'Capital ae' },
            { symbol: '&Ccedil;', title: 'Capital c with cedilla' },
            { symbol: '&Egrave;', title: 'Capital e with grave accent' },
            { symbol: '&Eacute;', title: 'Capital e with acute accent' },
            { symbol: '&Ecirc;', title: 'Capital e with circumflex accent' },
            { symbol: '&Euml;', title: 'Capital e with umlaut' },
            { symbol: '&Igrave;', title: 'Capital i with grave accent' },
            { symbol: '&Iacute;', title: 'Capital i with accute accent' },
            { symbol: '&Icirc;', title: 'Capital i with circumflex accent' },
            { symbol: '&Iuml;', title: 'Capital i with umlaut' },
            { symbol: '&ETH;', title: 'Capital eth (Icelandic)' },
            { symbol: '&Ntilde;', title: 'Capital n with tilde' },
            { symbol: '&Ograve;', title: 'Capital o with grave accent' },
            { symbol: '&Oacute;', title: 'Capital o with accute accent' },
            { symbol: '&Ocirc;', title: 'Capital o with circumflex accent' },
            { symbol: '&Otilde;', title: 'Capital o with tilde' },
            { symbol: '&Ouml;', title: 'Capital o with umlaut' },
            { symbol: '&Oslash;', title: 'Capital o with slash' },
            { symbol: '&Ugrave;', title: 'Capital u with grave accent' },
            { symbol: '&Uacute;', title: 'Capital u with acute accent' },
            { symbol: '&Ucirc;', title: 'Capital u with circumflex accent' },
            { symbol: '&Uuml;', title: 'Capital u with umlaut' },
            { symbol: '&Yacute;', title: 'Capital y with acute accent' },
            { symbol: '&THORN;', title: 'Capital thorn (Icelandic)' },
            { symbol: '&szlig;', title: 'Lowercase sharp s (German)' },
            { symbol: '&agrave;', title: 'Lowercase a with grave accent' },
            { symbol: '&aacute;', title: 'Lowercase a with acute accent' },
            { symbol: '&acirc;', title: 'Lowercase a with circumflex accent' },
            { symbol: '&atilde;', title: 'Lowercase a with tilde' },
            { symbol: '&auml;', title: 'Lowercase a with umlaut' },
            { symbol: '&aring;', title: 'Lowercase a with ring' },
            { symbol: '&aelig;', title: 'Lowercase ae' },
            { symbol: '&ccedil;', title: 'Lowercase c with cedilla' },
            { symbol: '&egrave;', title: 'Lowercase e with grave accent' },
            { symbol: '&eacute;', title: 'Lowercase e with acute accent' },
            { symbol: '&ecirc;', title: 'Lowercase e with circumflex accent' },
            { symbol: '&euml;', title: 'Lowercase e with umlaut' },
            { symbol: '&igrave;', title: 'Lowercase i with grave accent' },
            { symbol: '&iacute;', title: 'Lowercase i with acute accent' },
            { symbol: '&icirc;', title: 'Lowercase i with circumflex accent' },
            { symbol: '&iuml;', title: 'Lowercase i with umlaut' },
            { symbol: '&eth;', title: 'Lowercase eth (Icelandic)' },
            { symbol: '&ntilde;', title: 'Lowercase n with tilde' },
            { symbol: '&ograve;', title: 'Lowercase o with grave accent' },
            { symbol: '&oacute;', title: 'Lowercase o with acute accent' },
            { symbol: '&ocirc;', title: 'Lowercase o with circumflex accent' },
            { symbol: '&otilde;', title: 'Lowercase o with tilde' },
            { symbol: '&ouml;', title: 'Lowercase o with umlaut' },
            { symbol: '&oslash;', title: 'Lowercase o with slash' },
            { symbol: '&ugrave;', title: 'Lowercase u with grave accent' },
            { symbol: '&uacute;', title: 'Lowercase u with acute accent' },
            { symbol: '&ucirc;', title: 'Lowercase u with circumflex accent' },
            { symbol: '&uuml;', title: 'Lowercase u with umlaut' },
            { symbol: '&yacute;', title: 'Lowercase y with acute accent' },
            { symbol: '&thorn;', title: 'Lowercase thorn (Icelandic)' },
            { symbol: '&yuml;', title: 'Lowercase y with umlaut' }
        ]
    },
    {
        title: 'ISO-8859-1 Symbols',
        symbols: [
            { symbol: '&nbsp;', title: 'Non-breaking space' },
            { symbol: '&iexcl;', title: 'Inverted exclamation mark' },
            { symbol: '&cent;', title: 'Cent' },
            { symbol: '&pound;', title: 'Pound' },
            { symbol: '&curren;', title: 'Currency' },
            { symbol: '&yen', title: 'Yen' },
            { symbol: '&brvbar;', title: 'Broken vertical bar' },
            { symbol: '&sect;', title: 'Section' },
            { symbol: '&uml;', title: 'Spacing diaeresis' },
            { symbol: '&copy;', title: 'Copyright' },
            { symbol: '&ordf;', title: 'Feminine ordinal indicator' },
            { symbol: '&laquo;', title: 'Opening/Left angle quotation mark' },
            { symbol: '&not;', title: 'Negation' },
            { symbol: '&shy;', title: 'Soft hyphen' },
            { symbol: '&reg;', title: 'Registered trademark' },
            { symbol: '&macr;', title: 'Spacing macron' },
            { symbol: '&deg;', title: 'Degree' },
            { symbol: '&plusmn;', title: 'Plus or minus' },
            { symbol: '&sup2;', title: 'Superscript 2' },
            { symbol: '&sup3;', title: 'Superscript 3' },
            { symbol: '&acute;', title: 'Spacing acute' },
            { symbol: '&micro;', title: 'Micro' },
            { symbol: '&para;', title: 'Paragraph' },
            { symbol: '&cedil;', title: 'Spacing cedilla' },
            { symbol: '&sup1;', title: 'Superscript 1' },
            { symbol: '&ordm;', title: 'Masculine ordinal indicator' },
            { symbol: '&raquo;', title: 'Closing/Right angle quotation mark' },
            { symbol: '&frac14;', title: 'Fraction 1/4' },
            { symbol: '&frac12;', title: 'Fraction 1/2' },
            { symbol: '&frac34;', title: 'Fraction 3/4' },
            { symbol: '&iquest;', title: 'Inverted question mark' },
            { symbol: '&times;', title: 'Multiplication' },
            { symbol: '&divide;', title: 'Divide' }
        ]
    },
    {
        title: 'Math Symbols',
        symbols: [
            { symbol: '&forall;', title: 'For all' },
            { symbol: '&part;', title: 'Part' },
            { symbol: '&exist;', title: 'Exist' },
            { symbol: '&empty;', title: 'Empty' },
            { symbol: '&nabla;', title: 'Nabla' },
            { symbol: '&isin;', title: 'Is in' },
            { symbol: '&notin;', title: 'Not in' },
            { symbol: '&ni;', title: 'Ni' },
            { symbol: '&prod;', title: 'Product' },
            { symbol: '&sum;', title: 'Sum' },
            { symbol: '&minus;', title: 'Minus' },
            { symbol: '&lowast;', title: 'Asterisk (Lowast)' },
            { symbol: '&radic;', title: 'Square root' },
            { symbol: '&prop;', title: 'Proportional to' },
            { symbol: '&infin;', title: 'Infinity' },
            { symbol: '&ang;', title: 'Angle' },
            { symbol: '&and;', title: 'And' },
            { symbol: '&or;', title: 'Or' },
            { symbol: '&cap;', title: 'Cap' },
            { symbol: '&cup;', title: 'Cup' },
            { symbol: '&int;', title: 'Integral' },
            { symbol: '&there4;', title: 'Therefore' },
            { symbol: '&sim;', title: 'Similar to' },
            { symbol: '&cong;', title: 'Congurent to' },
            { symbol: '&asymp;', title: 'Almost equal' },
            { symbol: '&ne;', title: 'Not equal' },
            { symbol: '&equiv;', title: 'Equivalent' },
            { symbol: '&le;', title: 'Less or equal' },
            { symbol: '&ge;', title: 'Greater or equal' },
            { symbol: '&sub;', title: 'Subset of' },
            { symbol: '&sup;', title: 'Superset of' },
            { symbol: '&nsub;', title: 'Not subset of' },
            { symbol: '&sube;', title: 'Subset or equal' },
            { symbol: '&supe;', title: 'Superset or equal' },
            { symbol: '&oplus;', title: 'Circled plus' },
            { symbol: '&otimes;', title: 'Circled times' },
            { symbol: '&perp;', title: 'Perpendicular' },
            { symbol: '&sdot;', title: 'Dot operator' }
        ]
    },
    {
        title: 'Greek Letters',
        symbols: [
            { symbol: '&Alpha;', title: 'Alpha' },
            { symbol: '&Beta;', title: 'Beta' },
            { symbol: '&Gamma;', title: 'Gamma' },
            { symbol: '&Delta;', title: 'Delta' },
            { symbol: '&Epsilon;', title: 'Epsilon' },
            { symbol: '&Zeta;', title: 'Zeta' },
            { symbol: '&Eta;', title: 'Eta' },
            { symbol: '&Theta;', title: 'Theta' },
            { symbol: '&Iota;', title: 'Iota' },
            { symbol: '&Kappa;', title: 'Kappa' },
            { symbol: '&Lambda;', title: 'Lambda' },
            { symbol: '&Mu;', title: 'Mu' },
            { symbol: '&Nu;', title: 'Nu' },
            { symbol: '&Xi;', title: 'Xi' },
            { symbol: '&Omicron;', title: 'Omicron' },
            { symbol: '&Pi;', title: 'Pi' },
            { symbol: '&Rho;', title: 'Rho' },
            { symbol: '&Sigma;', title: 'Sigma' },
            { symbol: '&Tau;', title: 'Tau' },
            { symbol: '&Upsilon;', title: 'Upsilon' },
            { symbol: '&Phi;', title: 'Phi' },
            { symbol: '&Chi;', title: 'Chi' },
            { symbol: '&Psi;', title: 'Psi' },
            { symbol: '&Omega;', title: 'Omega' },
            { symbol: '&alpha;', title: 'alpha' },
            { symbol: '&beta;', title: 'beta' },
            { symbol: '&gamma;', title: 'gamma' },
            { symbol: '&delta;', title: 'delta' },
            { symbol: '&epsilon;', title: 'epsilon' },
            { symbol: '&zeta;', title: 'zeta' },
            { symbol: '&eta;', title: 'eta' },
            { symbol: '&theta;', title: 'theta' },
            { symbol: '&iota;', title: 'iota' },
            { symbol: '&kappa;', title: 'kappa' },
            { symbol: '&lambda;', title: 'lambda' },
            { symbol: '&mu;', title: 'mu' },
            { symbol: '&nu;', title: 'nu' },
            { symbol: '&xi;', title: 'xi' },
            { symbol: '&omicron;', title: 'omicron' },
            { symbol: '&pi;', title: 'pi' },
            { symbol: '&rho;', title: 'rho' },
            { symbol: '&sigmaf;', title: 'sigmaf' },
            { symbol: '&sigma;', title: 'sigma' },
            { symbol: '&tau;', title: 'tau' },
            { symbol: '&upsilon;', title: 'upsilon' },
            { symbol: '&phi;	  ', title: 'phi' },
            { symbol: '&chi;	  ', title: 'chi' },
            { symbol: '&psi;', title: 'psi' },
            { symbol: '&omega;', title: 'omega' },
            { symbol: '&thetasym;', title: 'Theta symbol' },
            { symbol: '&upsih;', title: 'Upsilon symbol' },
            { symbol: '&piv;', title: 'Pi symbol' }
        ]
    },
    {
        title: 'Miscellaneous HTML entities',
        symbols: [
            { symbol: '&#338;', title: 'Uppercase ligature OE' },
            { symbol: '&#339;', title: 'Lowercase ligature OE' },
            { symbol: '&#352;', title: 'Uppercase S with caron' },
            { symbol: '&#353;', title: 'Lowercase S with caron' },
            { symbol: '&#376;', title: 'Capital Y with diaeres' },
            { symbol: '&#402;', title: 'Lowercase with hook' },
            { symbol: '&#710;', title: 'Circumflex accent' },
            { symbol: '&#732;', title: 'Tilde' },
            { symbol: '&#8194;', title: 'En space' },
            { symbol: '&#8195;', title: 'Em space' },
            { symbol: '&#8201;', title: 'Thin space' },
            { symbol: '&#8204;', title: ' Zero width non-joiner' },
            { symbol: '&#8205;', title: ' Zero width joiner' },
            { symbol: '&#8206;', title: 'Left-to-right mark' },
            { symbol: '&#8207;', title: 'Right-to-left mark' },
            { symbol: '&#8211;', title: 'En dash' },
            { symbol: '&#8212;', title: 'Em dash' },
            { symbol: '&#8216;', title: 'Left single quotation mark' },
            { symbol: '&#8217;', title: 'Right single quotation mark' },
            { symbol: '&#8218;', title: 'Single low-9 quotation mark' },
            { symbol: '&#8220;', title: 'Left double quotation mark' },
            { symbol: '&#8221;', title: 'Right double quotation mark' },
            { symbol: '&#8222;', title: 'Double low-9 quotation mark' },
            { symbol: '&#8224;', title: 'Dagger' },
            { symbol: '&#8225;', title: 'Double dagger' },
            { symbol: '&#8226;', title: 'Bullet' },
            { symbol: '&#8230;', title: 'Horizontal ellipsis' },
            { symbol: '&#8240;', title: 'Per mille' },
            { symbol: '&#8242;', title: 'Minutes (Degrees)' },
            { symbol: '&#8243;', title: 'Seconds (Degrees)' },
            { symbol: '&#8249;', title: 'Single left angle quotation' },
            { symbol: '&#8250;', title: 'Single right angle quotation' },
            { symbol: '&#8254;', title: 'Overline' },
            { symbol: '&#8364;', title: 'Euro' },
            { symbol: '&#8482;', title: 'Trademark' },
            { symbol: '&#8592;', title: 'Left arrow' },
            { symbol: '&#8593;', title: 'Up arrow' },
            { symbol: '&#8594;', title: 'Right arrow' },
            { symbol: '&#8595;', title: 'Down arrow' },
            { symbol: '&#8596;', title: 'Left right arrow' },
            { symbol: '&#8629;', title: 'Carriage return arrow' },
            { symbol: '&#8968;', title: 'Left ceiling' },
            { symbol: '&#8969;', title: 'Right ceiling' },
            { symbol: '&#8970;', title: 'Left floor' },
            { symbol: '&#8971;', title: 'Right floor' },
            { symbol: '&#9674;', title: 'Lozenge' },
            { symbol: '&#9824;', title: 'Spade' },
            { symbol: '&#9827;', title: 'Club' },
            { symbol: '&#9829;', title: 'Heart' },
            { symbol: '&#9830;', title: 'Diamond' },
        ]
    }
]

